# Generated by Django 4.2.16 on 2024-10-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_application', '0003_product_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
